baseURL: https://yahui-yang.netlify.app/
googleAnalytics: UA/G-123123-12
languageCode: en-us
enableEmoji: yes
theme: avicenna
title: Yahui Yang
paginate: 10
markup:
  tableOfContents:
    endLevel: 3
    ordered: no
    startLevel: 1
params:
  name: Yahui Yang
